### ISSUE TITLE
这个常用列表有滚动条真让人难受O(∩_∩)O哈哈~

### ISSUE THREAD

**Issue by SwankyTigerYY** [chansee97/nova-admin#10]
这样排版会不会好一点儿
![image](https://github.com/chansee97/nova-admin/assets/24326903/8f3ce5c6-1788-414b-a7c2-3cec2994839c)
table再加个可拖拽的配置项，用在菜单那。省的一个一个编辑PID关联关系了。

写的很好，给作者点赞

**Comment by chansee97** [comment]
这个页面只是展示一下常见表单页面布局，具体项目中可以根据需要自行调整，如果加入了上图中的隐藏改动，在不同尺寸下，最右侧的操作按钮任然会被挤压。
关于菜单的pid关联，参考菜单管理页面，在编辑弹框中可以通过下拉选择来修改父级，拖拽编辑的需求并不大
