### ISSUE TITLE
【功能建议】建议使用git tag功能标注稳定版本

### ISSUE THREAD

**Issue by cvpv** [chansee97/nova-admin#11]
个人建议使用版本号标注版本，比如两小时前发布的[feat: add multi layout](https://github.com/chansee97/nova-admin/commit/4d27fe76d6afac183c20bcef14587b041cd50357)，这样做就可以在文档（vite press搞一个），写更新日志了。我个人觉得蛮有意思的。

**Comment by cvpv** [comment]
看版本号迭代也蛮有成就感，

**Comment by cvpv** [comment]
还可以引导用户下载稳定版本，不要直接fork主分支

**Comment by chansee97** [comment]
vitepress文档已同步更新，关于tag版本即将使用

**Comment by cvpv** [comment]
好的，大佬
