### ISSUE TITLE
vscode render函数渲染jsx语法报错

### ISSUE THREAD

**Issue by FreyaOne** [chansee97/nova-admin#15]
### Description

您好，在学习您的代码的过程中，有一个问题始终比较困扰
在account文件夹下的Index.vue文件中，使用了render函数去渲染组件，并使用了jsx语法，但是这在我的vscode中大量报红，搜寻了很多方法，尝试未果，这导致我的项目在运行老是在那行语句报错，想请问一下有什么好的解决办法吗？
<img width="498" alt="image" src="https://github.com/chansee97/nova-admin/assets/25958161/54a77959-41d7-47b0-a18f-c02675d27399">
<img width="862" alt="image" src="https://github.com/chansee97/nova-admin/assets/25958161/8856f85d-9503-4a7c-b395-d206e32004a7">

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by FreyaOne** [comment]
我刚提交完，就看到您在7个小时前提交了这个代码修复，牛的

**Comment by FreyaOne** [comment]
在拉取最新代码后，运行没有报错了，但是在编辑器中还是报红🥺

**Comment by chansee97** [comment]
可以运行`pnpm lint` 来检查项目中有无潜在的报错，如果没有任何报错，那爆红可能是编辑器插件冲突的问题，关于这个我没法帮你解决

**Comment by chansee97** [comment]
看看编辑器报红提示什么，看看能不能根据提示解决

**Comment by FreyaOne** [comment]
感恩，玄学，重刷了好几次vscode后，就一下子就没了
