### ISSUE TITLE
使用本地SVG渲染菜单图标

### ISSUE THREAD

**Issue by zhanglinweigithub** [chansee97/nova-admin#18]
### Description

请教一下：我想将项目中的菜单图标优先使用本地的svg图标，我应该如何改造项目。我在icon.ts中修改未生效

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
这个问题在处理了

**Comment by chansee97** [comment]
该功能已解决，现在返回的路由icon字段，如果是`local:`开头，则会自动加载本地svg，例如`"icon":"local:cool"`, 线上预览的图标示例页已使用该功能，如果无效请刷新缓存，菜的的icon选择器也同步修改可以选择本地svg
![image](https://github.com/chansee97/nova-admin/assets/90271994/5949b25e-4b5e-4e2e-90a3-04fff9c05be1)
![image](https://github.com/chansee97/nova-admin/assets/90271994/e6e05fa4-2960-41ff-971f-2850bd8eb3c3)

**Comment by chansee97** [comment]
该功能现在实现比较粗糙，如果有优化点和bug, 欢迎提交pr
