### ISSUE TITLE
启动起来登录页面样式错乱

### ISSUE THREAD

**Issue by sunxuecong** [chansee97/nova-admin#22]
### Description

启动起来登录页面样式错乱

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
请给出最小复现

**Comment by sunxuecong** [comment]
<img width="1391" alt="image" src="https://github.com/chansee97/nova-admin/assets/50600848/b1f36ca7-07e2-4eb0-8cc0-a0ad580d4e10">
<img width="1199" alt="image" src="https://github.com/chansee97/nova-admin/assets/50600848/73f5b9d9-42bb-42df-b5d4-ffc070af47a7">

**Comment by sunxuecong** [comment]
<img width="1176" alt="image" src="https://github.com/chansee97/nova-admin/assets/50600848/953147e4-6d37-45cc-9fad-860ccec60249">

**Comment by chansee97** [comment]
看起来组件自动导入并没有生效，尝试重启vite，或者删除node_modules重新拉取
