### ISSUE TITLE
角色管理，菜单权限，接口权限，api管理

### ISSUE THREAD

**Issue by wucenglou** [chansee97/nova-admin#25]
### Description

角色管理，菜单权限，接口权限，api管理。类似这里面的http://139.9.100.77:9999/login?redirect=/workbench

### Suggestion

不知道有没有打算做

### Additional context

![微信截图_20240711101801](https://github.com/chansee97/nova-admin/assets/29853622/9d2bca3b-bb8e-4395-87b0-7912527d5dec)
![微信截图_20240711101723](https://github.com/chansee97/nova-admin/assets/29853622/f6d203c5-89b5-49ff-9c56-fbc0c66b18d8)
![微信截图_20240711101733](https://github.com/chansee97/nova-admin/assets/29853622/21646a45-f4c8-4da3-a57b-2970237b78ba)

**Comment by chansee97** [comment]
角色管理，菜单权限后面会添加，接口管理，api管理暂不考虑
