### ISSUE TITLE
vscode打开代码很多报错

### ISSUE THREAD

**Issue by wthahaha** [chansee97/nova-admin#26]
### Description

大佬，createApp等vue的方法不用导入就可以使用吗？我的vscode上报错，不知道是不是没设置对
![微信截图_20240711160619](https://github.com/chansee97/nova-admin/assets/19517430/8dff7862-d6e4-4444-8798-28d60bfaee89)

### Expected

如何解决呢

### Validations

- [X] Ensure this issue not a bug proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
重启编辑器，createApp等方法使用了自动导入
