### ISSUE TITLE
Routing word error

### ISSUE THREAD

**Issue by merry-kugua** [chansee97/nova-admin#27]
### Description

路由文件当中的routes.static.ts 中documents/vue，而不是你现在写的docments,以及，i18n 文件中的单词错误等，作为一个开源框架，这种基础的问题是不应该出现的，希望更正一下

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
感谢指正，已修改
