### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by KDWLL-GitHub** [chansee97/nova-admin#28]
### Description

打包部署后页面空白有报错：
![image](https://github.com/user-attachments/assets/4a8a2ec5-80be-4608-8d8d-10019f782dde)
![image](https://github.com/user-attachments/assets/6664219c-f2a0-4dd7-a226-1a7715c72aac)
好像是取环境配置变量时属性名称不对应

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [x] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
打包时需要指定正确的环境标识`mode`字段

**Comment by chansee97** [comment]
例如`vite build --mode prod`
