### ISSUE TITLE
类型实例化过深，且可能无限。ts-plugin(2589)

### ISSUE THREAD

**Issue by gopower** [chansee97/nova-admin#29]
### Description

![image](https://github.com/user-attachments/assets/e68dc046-f7b6-4089-bf8e-b9b6595f9446)

### Expected

sideMenu.value = targetMenu.children ? targetMenu.children : [targetMenu]
类型实例化过深，且可能无限。ts-plugin(2589)

### Validations

- [X] Ensure this issue not a bug proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
我在本地没有出现这个问题。。
