### ISSUE TITLE
Upgrade Depenncy  alova to version alova@3.0.4.

### ISSUE THREAD

**Issue by gopower** [chansee97/nova-admin#30]
### Description

Upgrade Depenncy  alova to version alova@3.0.4.

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
upgraded
