### ISSUE TITLE
用户设置界面不能新增/修改部门

### ISSUE THREAD

**Issue by smuki** [chansee97/nova-admin#31]
### Description

![局部截取_20240804_130745](https://github.com/user-attachments/assets/606f7f62-2ed0-4edc-9baa-9c6ac5a00e3b)
![局部截取_20240804_130950](https://github.com/user-attachments/assets/0ce89aba-9c03-411f-9fe7-170fb05e8cbd)

### Suggestion

用户设置界面不能新增/修改部门

### Validations

- [X] Ensure this issue not a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
仅为示例
