### ISSUE TITLE
当配置了带参数的路由的同时，也配置了静态路由，组件获取不到参数

### ISSUE THREAD

**Issue by Guanxinyi-cookies** [chansee97/nova-admin#33]
### Description

想配置像如下的带参数路由，根据参数不同请求不同数据。
但是同时又想添加一个静态路由固定加载到菜单上。
此时页面加载正常，但是router.param获取不到参数。
怀疑是因为match了最后添加的power-home/1的静态路由，
不过在之前的vue2项目中，这么写可以获取到参数。
![image](https://github.com/user-attachments/assets/ce98f82f-9930-4ff3-8e8d-05d78d6a116d)
![image](https://github.com/user-attachments/assets/e25a276f-1c0e-45ac-ba2c-ada5bf37ce49)

是否有合适的解决方案？

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
power-home/1 路径显式声明我觉得确实不应该能拿到param=1，我觉得可以将两个路径合为一个，param取值时给默认值1更合理

**Comment by Guanxinyi-cookies** [comment]
感谢您的回复，不过我没有很理解`两个路径合为一个，param取值时给默认值1更合理`这句话的含义，因为想在routes.static.ts中直接声明这个菜单，所以直接写死了。
另外，刚才我在其他工程测试了一下，似乎是能够拿到的
下面是路由定义:
![image](https://github.com/user-attachments/assets/1b39f23d-c415-4e9a-9d10-d89b6a1b12d1)
组件内代码：
![image](https://github.com/user-attachments/assets/9f04a79d-45ed-4592-a74a-185669a75fe0)
运行结果：
![image](https://github.com/user-attachments/assets/1ec0eaee-a198-4a23-a96e-c1f04d2f16be)
![image](https://github.com/user-attachments/assets/54a54c73-903a-42b8-884f-7a985bbe1502)

静态和传参都能获取值
工程引用的vue-router版本为4.4.0

**Comment by Guanxinyi-cookies** [comment]
补充：成功获取参数的代码中，打印route,matched只有一个
![image](https://github.com/user-attachments/assets/092dd41f-d666-4c08-b0d5-d408de009669)

**Comment by chansee97** [comment]
试了一下query和param方式都有问题，我并没有对path字段做什么处理，不太清楚这个问题的原因，你可以写2个页面，比如一个为/test/main ，从该页面重定向到/test/1 ,首页菜单固定路径为test/main

**Comment by chansee97** [comment]
直接在路径中声明query和param，参数部分直接变成路径的一部分导致没有捕获到参数。。。

**Comment by Guanxinyi-cookies** [comment]
我大概发现了问题，您这边可以确认下。
首先对于参数路由的话，配置静态路由的时候如果配置了name和component,也许会影响路由的匹配，控制台打印如下
![image](https://github.com/user-attachments/assets/4c6f6d5e-14ae-4edc-bfc2-bf1178f8cdbf)
当取消name和component配置的控制台：
![image](https://github.com/user-attachments/assets/5865f29f-c66c-4c30-afcd-7759d1863ee9)

然后是当父菜单未配置重定向时，框架会自己分配一个子菜单
![image](https://github.com/user-attachments/assets/563f2a4a-8162-4c02-8cf7-34c8cbdc0e1f)
当父菜单是带参数的路由时，这似乎也会导致匹配问题，match也会出现配置的静态路由，我把这段代码注释后就正常了：
注释前：
![image](https://github.com/user-attachments/assets/799c5407-a170-4325-9cca-d4dedcc77c31)
注释后：
![image](https://github.com/user-attachments/assets/29c87139-cf80-4d43-9e4a-e55c32f9e725)
成功获取了params
最终解决方式，不修改框架代码的情况下，子菜单上移除了name和component配置，不在父菜单做路由匹配，新增了一个隐藏的子菜单做路由匹配
![image](https://github.com/user-attachments/assets/e229f754-a893-4382-aee7-9368cd2f79bf)
![image](https://github.com/user-attachments/assets/65daa7ef-8704-4d0e-a54c-218accac9db4)

**Comment by Guanxinyi-cookies** [comment]
这么写还是有点小问题，面包屑的显示不正确，而且点击时会跳转到动态参数地址
![image](https://github.com/user-attachments/assets/0ef74692-2b3d-4f4c-9b6c-d26fb17e433d)
![image](https://github.com/user-attachments/assets/cb3073ae-63d8-4aa1-97bc-d571a6bf4dd3)
