### ISSUE TITLE
示例优化-这几个在dark模式下背景颜色没有适配

### ISSUE THREAD

**Issue by zddgg** [chansee97/nova-admin#35]
### Description

功能示例-请求示例
功能示例-省市区联动
功能示例-字典示例

### Suggestion

1

### Validations

- [X] Ensure this issue not a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
仅作数据展示，无需适配

**Comment by chansee97** [comment]
已修改
