### ISSUE TITLE
有个小疑问没看明白，是怎么实现store安装完成在控制台打印的log日志的，如果需要关闭该怎么实现呢，求大佬解答一下

### ISSUE THREAD

**Issue by cailianghua** [chansee97/nova-admin#37]
### Description

![image](https://github.com/user-attachments/assets/dd4830a1-9efd-4bcb-acf3-badf8e37137d)

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
https://github.com/vuejs/pinia/discussions/2703

**Comment by cailianghua** [comment]
明白了
