### ISSUE TITLE
侧边栏与标签混个点击导致控制台报错，页面无法渲染

### ISSUE THREAD

**Issue by zhanglinweigithub** [chansee97/nova-admin#41]
### Description

![image](https://github.com/user-attachments/assets/548b79bc-4e64-4c2d-b023-9bcd5e82839e)
这俩个位置交叉点击会导致控制到报错，无法渲染页面（已注释keepAlive仍未解决）
![image](https://github.com/user-attachments/assets/606df9b5-827b-471c-95d7-cfbd6ce14cb2)

### Expected

搞了好久没解决，期待大佬给个解决方案

### Validations

- [X] Ensure this issue not a bug proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by zhanglinweigithub** [comment]
检查过菜单数据了，没问题呀，都是以下模板，而且是偶发的
![image](https://github.com/user-attachments/assets/d51bdb79-6dcb-4ede-9549-f5944e12fc0c)

**Comment by chansee97** [comment]
示例站点如果无法复现则无法处理
