### ISSUE TITLE
不知道怎么配置成功

### ISSUE THREAD

**Issue by liuhanyun99** [chansee97/nova-admin#42]
### Description

我下载了文件的压缩包，也解压了，但是不知道后面怎么配置成功，也不知道还要不要配置好其他的依赖，完全是新手，老师可以跟我说说吗

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [docs](https://nova-admin-docs.pages.dev/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
https://nova-admin-docs.pages.dev/zh/ 请阅读文档，提出更加具体的问题
