### ISSUE TITLE
登录后出现404

### ISSUE THREAD

**Issue by hsb0307** [chansee97/nova-admin#5]
pnpm run dev ， 登录， 进入了 /dashboard/workbench， 显示为 404，是什么原因 ？

**Comment by chansee97** [comment]
我使用无痕模式打开项目并没有出现这个问题，可以拉取新代码重试
一般出现这个问题是因为请求的路径不在路由表当中

**Comment by chansee97** [comment]
> > 我使用无痕模式打开项目并没有出现这个问题，可以拉取新代码重试 一般出现这个问题是因为请求的路径不在路由表当中
> 
> 没什么用开无痕照样404

我已经同步了gitee代码，应该没有问题了
